### ISSUE TITLE
[ISSUE]ON PART SEGEMENTATION IN SHAPENET PAER

### ISSUE THREAD

**Issue by yuchenlichuck** [tiangexiang/CurveNet#4]
HI, XIANG, 
I found the code in part segmentation is wrong. Could you check with the code please?
```
mv: cannot stat 'shapenet_part_seg_hdf5_data': No such file or directory
Traceback (most recent call last):
  File "main_partseg.py", line 346, in <module>
    train(args, io)
  File "main_partseg.py", line 85, in train
    train_dataset = ShapeNetPart(partition='trainval', num_points=args.num_points, class_choice=args.class_choice)
  File "/home/liy0r/3d-few-shot/download/CurveNet/core/data.py", line 158, in __init__
    self.data, self.label, self.seg = load_data_partseg(partition)
  File "/home/liy0r/3d-few-shot/download/CurveNet/core/data.py", line 91, in load_data_partseg
    all_data = np.concatenate(all_data, axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
```

**Comment by yuchenlichuck** [comment]
small mistake, i think in the 
def download_shapenetpart():
You need to first mkdir `"shapenet_part_seg_hdf5_data"`

**Comment by tiangexiang** [comment]
Ooops, thanks for the fix, the PR has now been merged.

**Comment by tiangexiang** [comment]
Ooops, thanks for the fix, the PR has now been merged.
