### ISSUE TITLE
About classification modelnet40_normal？

### ISSUE THREAD

**Issue by swzaaaaaaa** [tiangexiang/CurveNet#8]
Traceback (most recent call last):
  File "main_normal.py", line 208, in <module>
    train(args, io)
  File "main_normal.py", line 46, in train
    train_loader = DataLoader(ModelNetNormal(args.num_points, partition='train'), 
  File "/opt/data/private/swz/CurveNet-main/core/data.py", line 140, in __init__
    self.data, self.label = load_data_normal(partition)
  File "/opt/data/private/swz/CurveNet-main/core/data.py", line 51, in load_data_normal
    f = h5py.File(os.path.join(DATA_DIR, 'modelnet40_normal', 'normal_%s.h5'%partition), 'r+')
  File "/root/anaconda3/envs/pytorch_swz/lib/python3.8/site-packages/h5py/_hl/files.py", line 442, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/root/anaconda3/envs/pytorch_swz/lib/python3.8/site-packages/h5py/_hl/files.py", line 197, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '../data/modelnet40_normal/normal_train.h5', errno = 2, error message = 'No such file or directory', flags = 1, o_flags = 2)

**Comment by tiangexiang** [comment]
Hi, can you please double check the modelnet40_normal data is indeed at the right place? i.e. '../data/modelnet40_normal/normal_train.h5' ?

**Comment by swzaaaaaaa** [comment]
modelnet40_normal 这是数据集是哪个，我看modelnet40_ply_hdf5_2048 没有啊。

**Comment by tiangexiang** [comment]
Yes, we processed the ModelNet40 normal datasets ourselves, please refer to [this section](https://github.com/tiangexiang/CurveNet#data-2) in README for details and downloads.

**Comment by swzaaaaaaa** [comment]
ok。thanks
